
relay:
  verbose: false
  smtp_port: 5025
  smtp_host: "0.0.0.0"

server:
  host: "smtp.example.com"
  port: 587
  sender: "user@example.com"
  starttls: True
  auth:
    username: "user"
    password: "pass"
